import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        l<title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="keywords"
          content="nextjs, huntingCoder blog, hunting coder"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <img
            className={styles.myImg}
            src="/hpm.jpg"
            alt="hunting coder"
            width={237}
            height={158}
          />
        </div>
        <h1 className={styles.title}>
          <span className="dummy">&lt;HuntingCoder/&gt;</span>
        </h1>

        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p>
              JavaScript is the language used to design logic for the web. Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Ab, non!
            </p>
            <Link href="/blog">
              <button className={styles.btn}>Read More</button>
            </Link>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web. Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Vitae, illo?
            </p>
            <Link href="/blog">
              <button className={styles.btn}>Read More</button>
            </Link>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p>
              JavaScript is the language used to design logic for the web. Lorem
              ipsum dolor sit, amet consectetur adipisicing elit. Nulla,
              laborum.
            </p>
            <Link href="/blog">
              <button className={styles.btn}>Read More</button>
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
